# Application
spring.application.name=sgci-backend
server.port=8080

# H2 (développement)
spring.datasource.url=jdbc:h2:mem:sgcidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Console H2 (optionnel, pour debug)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Encodage
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# JWT (à remplacer en production par une clé forte et une variable d'environnement)
app.jwt.secret=SGCI-Secret-Key-Minimum-256-bits-For-HS256-Please-Change-In-Production
app.jwt.expiration-ms=86400000

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Taux de change (API externe)
# URL doit contenir {base}
app.exchange-rate.base=MRU
app.exchange-rate.url=https://open.er-api.com/v6/latest/{base}

# Exchangerate.host (convert EUR/USD -> MRU)
app.exchangerate.host.url=https://api.exchangerate.host
# Mettre la clé en variable d'environnement en prod (ex: APP_EXCHANGERATE_HOST_ACCESS_KEY)
app.exchangerate.host.access-key=6ded2d0c03b750cd8525a4ab8a2df010

# Logs (debug HTTP + sécurité)
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Dossier de stockage des documents uploadés (relatif au répertoire de travail ou chemin absolu)
app.upload.dir=uploads
# MinIO (stockage externe)
minio.url=https://archie-overlavish-virgie.ngrok-free.dev
minio.access-key=admin
minio.secret-key=password123
minio.bucket=documents
# Taille max fichier (10 Mo)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
