package mr.gov.finances.sgci.domain.enums;

public enum NotificationType {
    CORRECTION_STATUT_CHANGE,
    CORRECTION_DECISION,
    REFERENTIEL_STATUT_CHANGE,
    CONVENTION_STATUT_CHANGE,
    CERTIFICAT_STATUT_CHANGE,
    UTILISATION_STATUT_CHANGE,
    TRANSFERT_CREDIT,
    SOUS_TRAITANCE
}
