package mr.gov.finances.sgci.domain.enums;

public enum NotificationType {
    CORRECTION_STATUT_CHANGE,
    CORRECTION_DECISION,
    REFERENTIEL_STATUT_CHANGE,
    CONVENTION_STATUT_CHANGE,
    CERTIFICAT_STATUT_CHANGE,
    UTILISATION_STATUT_CHANGE,
    TRANSFERT_CREDIT,
    SOUS_TRAITANCE,
    DEMANDE_EXPLICATION,
    CLOTURE_CERTIFICAT,
    REJET_TEMP_DECISION,
    REJET_TEMP_RESOLU,
    REJET_TEMP_REPONSE,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_TRAITEE
}
