package mr.gov.finances.sgci.domain.enums;

public enum ProcessusDocument {
    CONVENTION,
    PROJET,
    MARCHE,
    CORRECTION_OFFRE_FISCALE,
    MISE_EN_PLACE_CI,
    MODIFICATION_CI,
    UTILISATION_CI,
    UTILISATION_CI_DOUANE,
    UTILISATION_CI_TVA_INTERIEURE,
    UTILISATION_CI_EXTERIEUR,
    UTILISATION_CI_INTERIEUR,
    TRANSFERT_CREDIT,
    SOUS_TRAITANCE,
    CLOTURE_CI
}
