package mr.gov.finances.sgci.domain.enums;

/**
 * Catalogue d'événements métier notifiables (in-app + e-mail).
 */
public enum WorkflowEventCode {
    // --- Correction ---
    CORRECTION_SOUMISE,
    CORRECTION_STATUT_CHANGE,
    CORRECTION_VISA,
    CORRECTION_REJET_TEMP,
    CORRECTION_REJET_DEFINITIF,
    CORRECTION_REJET_TEMP_REPONSE,
    CORRECTION_REJET_TEMP_RESOLU,
    CORRECTION_ADOPTEE,
    CORRECTION_RECLAMATION_DEPOSEE,
    CORRECTION_RECLAMATION_TRAITEE,
    CORRECTION_RECLAMATION_ANNULEE,

    // --- Certificat mise en place ---
    CERTIFICAT_SOUMIS,
    CERTIFICAT_STATUT_CHANGE,
    CERTIFICAT_PRISE_EN_CHARGE,
    CERTIFICAT_VISA,
    CERTIFICAT_REJET_TEMP,
    CERTIFICAT_REJET_TEMP_REPONSE,
    CERTIFICAT_REJET_TEMP_RESOLU,
    CERTIFICAT_PRESIDENT_VALIDATION,
    CERTIFICAT_OUVERT,

    // --- Utilisation douane ---
    UTIL_DOUANE_SOUMISE,
    UTIL_DOUANE_STATUT_CHANGE,
    UTIL_DOUANE_REJET_TEMP,
    UTIL_DOUANE_REJET_TEMP_REPONSE,
    UTIL_DOUANE_REJET_TEMP_RESOLU,
    UTIL_DOUANE_VISA_DGD,
    UTIL_DOUANE_CHEQUE,
    UTIL_DOUANE_TRESOR,
    UTIL_DOUANE_QUITTANCES,
    UTIL_DOUANE_LIQUIDEE,
    UTIL_DOUANE_CLOTUREE,
    UTIL_DOUANE_REJET_DEFINITIF,

    // --- Utilisation TVA intérieure ---
    UTIL_TVA_SOUMISE,
    UTIL_TVA_STATUT_CHANGE,
    UTIL_TVA_REJET_TEMP,
    UTIL_TVA_REJET_TEMP_REPONSE,
    UTIL_TVA_REJET_TEMP_RESOLU,
    UTIL_TVA_APUREE,
    UTIL_TVA_REJET_DEFINITIF,

    // --- Transfert ---
    TRANSFERT_DEMANDE,
    TRANSFERT_EN_COURS,
    TRANSFERT_REJET_TEMP,
    TRANSFERT_REJET_TEMP_REPONSE,
    TRANSFERT_REJET_TEMP_RESOLU,
    TRANSFERT_VALIDE,
    TRANSFERT_REJETE,
    TRANSFERT_ANNULE,

    // --- Clôture certificat ---
    CLOTURE_PROPOSEE,
    CLOTURE_APPROUVEE,
    CLOTURE_REJETEE,
    CLOTURE_FINALISEE
}
